In [1]:
import pandas as pd

In [2]:
data = pd.read_excel("step_1.xlsx")

In [3]:
data

,Unnamed: 0,Unnamed: 1,fis,sales,fis.1,sales.1,fis.2,sales.2,sam1,sales.3,...,sec2,sales.7,sec3,sales.8,sta1,sales.9,sta2,sales.10,sta3,Sales
0,CA-2011-100293,2013-03-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Home Office,91.056
1,CA-2011-100706,2013-12-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CA-2011-100895,2013-06-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Consumer,605.470,NaN,NaN,NaN,NaN
3,CA-2011-100916,2013-10-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Corporate,788.860,NaN,NaN
4,CA-2011-101266,2013-08-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
817,US-2014-166233,2016-07-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Consumer,24.000,NaN,NaN,NaN,NaN
818,US-2014-166611,2016-03-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Corporate,68.742,NaN,NaN
819,US-2014-167920,2016-12-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
820,US-2014-168116,2016-11-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
821,US-2014-168690,2016-01-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Consumer,2.808,NaN,NaN,NaN,NaN

In [4]:
first_class_cons = data[data["fis"] =="Consumer"]

In [5]:
first_class_cons

,Unnamed: 0,Unnamed: 1,fis,sales,fis.1,sales.1,fis.2,sales.2,sam1,sales.3,...,sec2,sales.7,sec3,sales.8,sta1,sales.9,sta2,sales.10,sta3,Sales
11,CA-2011-103366,2013-01-15,Consumer,149.950,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,CA-2011-109043,2013-08-15,Consumer,243.600,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,CA-2011-113166,2013-12-24,Consumer,9.568,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,CA-2011-124023,2013-04-07,Consumer,8.960,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,CA-2011-130155,2013-05-19,Consumer,34.200,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
769,US-2013-162677,2015-03-27,Consumer,187.616,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
772,US-2013-167472,2015-06-07,Consumer,678.870,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
778,US-2014-108063,2016-12-02,Consumer,34.650,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
794,US-2014-133781,2016-06-22,Consumer,37.608,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
803,US-2014-148831,2016-10-13,Consumer,348.560,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
first_class_cor = data[data["fis.1"] =="Corporate"]

In [9]:
first_class_cor

,Unnamed: 0,Unnamed: 1,fis,sales,fis.1,sales.1,fis.2,sales.2,sam1,sales.3,...,sec2,sales.7,sec3,sales.8,sta1,sales.9,sta2,sales.10,sta3,Sales
10,CA-2011-103317,2013-07-05,NaN,NaN,Corporate,242.546,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,CA-2011-103989,2013-03-19,NaN,NaN,Corporate,590.762,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,CA-2011-106054,2013-01-06,NaN,NaN,Corporate,12.780,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,CA-2011-111934,2013-05-05,NaN,NaN,Corporate,47.320,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,CA-2011-124688,2013-08-27,NaN,NaN,Corporate,1812.010,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,CA-2011-125682,2013-11-22,NaN,NaN,Corporate,9.960,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,CA-2011-131905,2013-02-06,NaN,NaN,Corporate,321.560,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
126,CA-2011-163293,2013-09-08,NaN,NaN,Corporate,116.850,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138,CA-2011-169684,2013-10-20,NaN,NaN,Corporate,426.942,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
153,CA-2012-104038,2014-02-06,NaN,NaN,Corporate,176.630,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
190,CA-2012-121720,2014-06-11,NaN,NaN,Corporate,3165.744,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
208,CA-2012-133396,2014-08-13,NaN,NaN,Corporate,64.680,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
223,CA-2012-140718,2014-07-02,NaN,NaN,Corporate,246.364,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
256,CA-2012-154746,2014-11-14,NaN,NaN,Corporate,860.070,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,CA-2012-156734,2014-06-18,NaN,NaN,Corporate,670.001,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
265,CA-2012-158323,2014-11-30,NaN,NaN,Corporate,17.088,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
318,CA-2013-112676,2015-05-06,NaN,NaN,Corporate,14.352,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
353,CA-2013-127208,2015-06-13,NaN,NaN,Corporate,224.900,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
365,CA-2013-133711,2015-11-27,NaN,NaN,Corporate,3236.410,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
412,CA-2013-153318,2015-10-26,NaN,NaN,Corporate,783.960,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
436,CA-2013-160598,2015-08-27,NaN,NaN,Corporate,31.008,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
441,CA-2013-162901,2015-03-29,NaN,NaN,Corporate,31.400,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
497,CA-2014-113481,2016-01-03,NaN,NaN,Corporate,740.214,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
505,CA-2014-115882,2016-09-14,NaN,NaN,Corporate,1017.136,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
511,CA-2014-117695,2016-08-05,NaN,NaN,Corporate,13.760,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
526,CA-2014-122707,2016-04-16,NaN,NaN,Corporate,503.220,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
531,CA-2014-123687,2016-05-26,NaN,NaN,Corporate,234.200,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
535,CA-2014-124828,2016-07-03,NaN,NaN,Corporate,9.552,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
557,CA-2014-129028,2016-04-01,NaN,NaN,Corporate,127.950,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
575,CA-2014-134810,2016-05-09,NaN,NaN,Corporate,272.232,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
612,CA-2014-147760,2016-11-04,NaN,NaN,Corporate,1883.724,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
636,CA-2014-155698,2016-03-08,NaN,NaN,Corporate,668.540,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
652,CA-2014-159464,2016-05-18,NaN,NaN,Corporate,524.850,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
666,CA-2014-161851,2016-04-15,NaN,NaN,Corporate,15.570,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
721,US-2012-131842,2014-12-05,NaN,NaN,Corporate,97.424,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
734,US-2013-101616,2015-09-04,NaN,NaN,Corporate,87.280,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
754,US-2013-140809,2015-02-01,NaN,NaN,Corporate,56.450,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
763,US-2013-153815,2015-11-07,NaN,NaN,Corporate,368.432,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
789,US-2014-128951,2016-07-15,NaN,NaN,Corporate,1065.840,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
812,US-2014-162208,2016-08-27,NaN,NaN,Corporate,2.896,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
first_class_hom = data[data["fis.2"] =="Home Office"]

In [12]:
first_class_hom

,Unnamed: 0,Unnamed: 1,fis,sales,fis.1,sales.1,fis.2,sales.2,sam1,sales.3,...,sec2,sales.7,sec3,sales.8,sta1,sales.9,sta2,sales.10,sta3,Sales
69,CA-2011-132010,2013-10-13,NaN,NaN,NaN,NaN,Home Office,389.740,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,CA-2011-136567,2013-12-20,NaN,NaN,NaN,NaN,Home Office,2884.370,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,CA-2011-140165,2013-05-13,NaN,NaN,NaN,NaN,Home Office,405.456,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
404,CA-2013-149454,2015-07-26,NaN,NaN,NaN,NaN,Home Office,10.440,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
428,CA-2013-159142,2015-04-05,NaN,NaN,NaN,NaN,Home Office,177.780,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
437,CA-2013-162159,2015-09-17,NaN,NaN,NaN,NaN,Home Office,121.780,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
520,CA-2014-121419,2016-04-02,NaN,NaN,NaN,NaN,Home Office,771.800,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
565,CA-2014-132213,2016-04-25,NaN,NaN,NaN,NaN,Home Office,109.968,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
597,CA-2014-144456,2016-09-08,NaN,NaN,NaN,NaN,Home Office,220.056,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
635,CA-2014-155292,2016-10-30,NaN,NaN,NaN,NaN,Home Office,204.980,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
766,US-2013-158309,2015-11-27,NaN,NaN,NaN,NaN,Home Office,3.744,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
813,US-2014-162558,2016-10-02,NaN,NaN,NaN,NaN,Home Office,2437.672,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
first_class_cons.to_excel("first_class_cons1.xlsx")

In [15]:
first_class_cor.to_excel("first_class_cor.xlsx")

In [16]:
first_class_hom.to_excel("first_class_hom.xlsx")

In [17]:
#

In [19]:
same_day_cons = data[data["sam1"] =="Consumer"]

In [38]:
same_day_cor= data[data["sam2"] =="Corporate"]

In [39]:
same_day_hom= data[data["sam3"] =="Home Office"]

In [23]:
same_day_cons.to_excel("same_day_cons.xlsx")

In [40]:
same_day_cor.to_excel("same_day_cor.xlsx")

In [41]:
same_day_hom.to_excel("same_day_hom.xlsx")

In [26]:
second_class_cons = data[data["sec1"] =="Consumer"]

In [27]:
second_class_cor = data[data["sec2"] =="Corporate"]

In [28]:
second_class_hom = data[data["sec3"] =="Home Office"]

In [29]:
second_class_hom.to_excel("second_class_hom.xlsx")

In [30]:
second_class_cons.to_excel("second_class_cons.xlsx")

In [42]:
second_class_cor.to_excel("second_class_cor.xlsx")

In [32]:
standard_class_cons = data[data["sta1"] =="Consumer"]

In [33]:
standard_class_cor = data[data["sta2"] =="Corporate"]

In [34]:
standard_class_hom = data[data["sta3"] =="Home Office"]

In [35]:
standard_class_cons.to_excel("standard_class_cons.xlsx")

In [36]:
standard_class_cor.to_excel("standard_class_cor.xlsx")

In [37]:
standard_class_hom.to_excel("standard_class_hom.xlsx")